### ISSUE TITLE
Auto-off doesn't work at longer timeouts (may be related to polling app).

### ISSUE THREAD

**Issue by jeremyk** [Z-Wave-Me/home-automation#283]
When using longer times (like 2 minutes) the auto-off app fails to work. Shorter times like 10 seconds work fine. I also have the polling app set to poll every minute. Maybe they are interfering with eachother as turning off polling fixes the auto-off app. Also, I see errors like this in the events list which may be related??

core	11:52 | Can't register duplicate module instance 17	Toggle Dropdown
core	11:52 | Cannot stop module 17: Error: clearTimeout()/clearInterval() mismatch

**Comment by PoltoS** [comment]
I believe here we see two different problems:
1) polling indeed instructs this module restart the timer. so, polling matters.
2) the second require more logs - looks like some module (may be not this one) have a mismatch of timers: setting it using setTimeout and clearing using clearInterval. I remember, we fixed this bug in this module (so, you might have old Z-Way). And just fixed it in AutoLock module.

**Comment by ronie-z-wave** [comment]
Indeed:

https://github.com/Z-Wave-Me/home-automation/commit/081863b8dfdb13330dbb2367d1439eeb1fe59645

But this should only occur if you deactivate or stop this module. 
Hmm, but why should polling influence AutoOff? It sends only 'update' command to get current device state. AutoOff should only recognize the changes of a switch 'on' or 'off' ... 
Sounds that everytime yor switch is triggered by polling, it send's only the state 'on' or 'off', so we'll need test if app 'Periodical Switch Polling' works correct.

**Comment by jeremyk** [comment]
I was running v2.1.2-rc2 but not sure how to tell if either of those commits are included.

**Comment by jeremyk** [comment]
I updated to v2.1.2-rc9-internal but I am still seeing this issue. I set auto-off to 120s and polling to 1 minute and it never turns off. If I deactivate the polling app it turns off as expected.

**Comment by jeremyk** [comment]
Also when upgrading to rc9 homekit stopped working for my 1 switch. I tried removing and re-adding but the pairing process always failed. I went back to rc2 and was able to add it again. Should I file a separate issue for this or is it known?

**Comment by PoltoS** [comment]
It will not be fixed, since this is "by design". We will add a special flag "reset timer on value update".

HK, please separate it in another bug.

**Comment by jeremyk** [comment]
Hmm. Not sure I follow - seems like the timers for the two should be separate? Anyway, I will file the other issue.

**Comment by PoltoS** [comment]
863a7797a44f72d6667d16b051f9608b42725d25
